import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Button } from '@material-ui/core'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FP Model Simulation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{margin: "100px"}}>
          FP Model Simulation
        </h1>
        <Button variant="contained"><Link href="/simple_dynamics">シュミレーションページへ</Link></Button>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
